apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: skillpulse
spec:
  replicas: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rohinidivekar123/skillpulse-frontend:22c145ec43f1f9f8ab311d41b416609f4f53179c
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              memory: 64Mi

