apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mysql
  namespace: skillpulse

spec:
  serviceName: mysql
  replicas: 0

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: mysql:8.4

          ports:
            - containerPort: 3306

          envFrom:
            - secretRef:
                name: skillpulse-db

          volumeMounts:
            - name: init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true

          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 10
            periodSeconds: 5

      volumes:
        - name: init
          configMap:
            name: mysql-init
